kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-volume-0
  labels:
    type: local
spec:
  #storageClassName: local
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/redis/0"
